spring.application.name=session9-md4-jv2508
spring.datasource.url=jdbc:mysql://localhost:3306/session09_md4_jv2508?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088
cloudinary_name=dbtbegrpq
cloudinary_api_key=765277277933472
cloudinary_api_secret=a7GtpQB_mJxphkNzF40HbB5MXK8
